### ISSUE TITLE
好像不能用了！

### ISSUE THREAD

**Issue by bat-coco** [beichenhpy/Pxxnhook#1]
导入以后，启动状态下不能用！！！

**Comment by beichenhpy** [comment]
我这边测试可以正常使用，不要下载release版本的，直接用最新的

**Comment by beichenhpy** [comment]
我又release了一版，可以下载1.1版测试一下

**Comment by bat-coco** [comment]
baidu.cm 这站没了....................

**Comment by bat-coco** [comment]
> 我又发布了一版，可以下载1.1版测试一下
baidu.cm这站没了....................

**Comment by beichenhpy** [comment]
> > 我又发布了一版，可以下载1.1版测试一下
> > baidu.cm这站没了....................

看一下bg.js 里面我又加了两个他的备用站点，你可以试一下

**Comment by beichenhpy** [comment]
> > > 我又发布了一版，可以下载1.1版测试一下
> > > baidu.cm这站没了....................
> 
> 看一下bg.js 里面我又加了两个他的备用站点，你可以试一下

我这边看这个站还在。。

**Comment by bat-coco** [comment]
> > > > 我又发布了一版，可以下载1.1版测试一下
> > > > baidu.cm这站没了....................
> > 
> > 
> > 看一下bg.js里面我又加了两个他的备用站点，你可以试一下
> 
> 我这边看这个站还在。。

站又回来了，但是依旧不能用，插件名字jshooker1.0.0，开启状态下，打开网站baidu.cm，网站依旧需要登录 有限制！

**Comment by bat-coco** [comment]
> > > > > 我又发布了一版，可以下载1.1版测试一下
> > > > > baidu.cm这站没了....................
> > > 
> > > 
> > > 看一下bg.js里面我又加了两个他的备用站点，你可以试一下
> > 
> > 
> > 我这边看这个站还在。。
> 
> 站又回来了，但是依旧不能用，插件名称jshooker1.0.0，开启状态下，打开网站baidu.cm，网站依旧需要登录有限制！

Google浏览器插件加载的，浏览器版本版本 86.0.4240.75 (正式版本) (64 位元)
