### ISSUE TITLE
yrav2.com网站已经更新！！！！

### ISSUE THREAD

**Issue by bat-coco** [beichenhpy/Pxxnhook#3]
yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！

**Comment by beichenhpy** [comment]
> yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！

他们上新版本了，我针对上个版本爬了1900多个视频源，你可以用m3u8下载器下载，具体项目为
pxxn

**Comment by beichenhpy** [comment]
> yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！

兄弟，我更新了，使用release 1.2版本，直接可以看所有，最近有点忙

**Comment by beichenhpy** [comment]
> yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！

兄弟，我更新了，使用release 1.2版本，直接可以看所有，最近有点忙

**Comment by beichenhpy** [comment]
> yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！yrav2.com网站已经更新！！！！

兄弟，我又更新了一版 release 这回支持了新的 www.yrav2.com ，但是需要登录，给你个可以登录的账号
```
1010@qq.com
123456
```

**Comment by bat-coco** [comment]
> > yrav2.com网站已经更新！！！！ yrav2.com网站已经更新！！！！
> 
> 兄弟，我又更新了一版发布这回支持了新的[www.yrav2.com](http://www.yrav2.com)，但是需要登录，给你个可以登录的账号
> 
> ```
> 1010@qq.com
> 123456
> ```

大哥，每次你更新以后，好像我都不能用，哈哈哈哈哈，我不知道为什么，可能是我没操作好，我吧封装导入了，然后也登录账号了，还是让充值！

**Comment by beichenhpy** [comment]
> > > yrav2.com网站已经更新！！！！ yrav2.com网站已经更新！！！！
> > 
> > 兄弟，我又更新了一版发布这回支持了新的[www.yrav2.com](http://www.yrav2.com)，但是需要登录，给你个可以登录的账号
> > 
> > ```
> > 1010@qq.com
> > 123456
> > ```
> 
> 大哥，每次你更新以后，好像我都不能用，哈哈哈哈哈，我不知道为什么，可能是我没操作好，我把封装导入了，然后也登录账号了，还是让充值！

奇了怪了，发个操作录屏给我邮箱吧，beichenhpy@outlook.com

**Comment by beichenhpy** [comment]
> > > yrav2.com网站已经更新！！！！ yrav2.com网站已经更新！！！！
> > 
> > 
> > 兄弟，我又更新了一版发布这回支持了新的[www.yrav2.com](http://www.yrav2.com)，但是需要登录，给你个可以登录的账号
> > ```
> > 1010@qq.com
> > 123456
> > ```
> 
> 大哥，每次你更新以后，好像我都不能用，哈哈哈哈哈，我不知道为什么，可能是我没操作好，我把封装导入了，然后也登录账号了，还是让充值！

我知道了，他域名又改成www.yrav8.com 了，我又更新了，重新试一下

**Comment by bat-coco** [comment]
> > > > yrav2.com网站已经更新！！！！！
> > > 
> > > 
> > > 兄弟，我又更新了一版发布这回支持了新的[www.yrav2.com](http://www.yrav2.com)，但是需要登录，给你个可以登录的账号
> > > ```
> > > 1010@qq.com
> > > 123456
> > > ```
> > 
> > 
> > 大哥，每次你更新以后，好像我都不能用，哈哈哈哈哈，我不知道为什么，可能是我没操作好，我把封装引入了，然后也登录账号了，还是让充值！
> 
> 我知道了，他域名又改成www.yrav8.com了，我又更新了，重新试一下

nice，可以看了！

**Comment by beichenhpy** [comment]
> > > > > yrav2.com网站已经更新！！！！！
> > > > 
> > > > 
> > > > 兄弟，我又更新了一版发布这回支持了新的[www.yrav2.com](http://www.yrav2.com)，但是需要登录，给你个可以登录的账号
> > > > ```
> > > > 1010@qq.com
> > > > 123456
> > > > ```
> > > 
> > > 
> > > 大哥，每次你更新以后，好像我都不能用，哈哈哈哈哈，我不知道为什么，可能是我没操作好，我把封装引入了，然后也登录账号了，还是让充值！
> > 
> > 我知道了，他域名又改成www.yrav8.com了，我又更新了，重新试一下
> 
> nice，可以看了！

注意身体，还有最好新注册一个用户，有异地登录验证，不要用真实的邮箱
